---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: api-gateway
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: api-gateway@sha256:fd82f811d8ecdbbeae06955c5f6deb956632ddd356e43ee523061009c535ac4a
        namespace: petclinic-develop
      name: 1.5.9
