---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 5cbef54bce52631c2c350271961dfa2f47602701
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=api-gateway&var-version=1.5.9
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/spring-petclinic-microservices/api-gateway
  labels:
    project: api-gateway
    version: 1.5.9
    app: api-gateway
    provider: fabric8
    group: org.springframework.samples.petclinic.api
  name: api-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api-gateway
      provider: fabric8
      group: org.springframework.samples.petclinic.api
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 5cbef54bce52631c2c350271961dfa2f47602701
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=api-gateway&var-version=1.5.9
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/spring-petclinic-microservices/api-gateway
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        project: api-gateway
        version: 1.5.9
        app: api-gateway
        provider: fabric8
        group: org.springframework.samples.petclinic.api
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: api-gateway:1.5.9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
        securityContext:
          privileged: false
